### ISSUE TITLE
Project opening Issue

### ISSUE THREAD

**Issue by modzking4** [4d-depot/HDI_OAuth2_Microsoft_mail#1]
I'm currently looking at this example and trying to open the project in version 19.4, how ever when trying to open the project I am greeted by and error saying to use a version of 4D newer than 19.3.
![Capture](https://user-images.githubusercontent.com/45033165/199512533-ec581379-7dfe-4e29-9594-533451f1591c.PNG)

**Comment by fabrice-mainguene** [comment]
Hi,

This example is only available with the v19 Release (R) 3.
The v19.4 is not a release version, so you can't use it
